// Named settings sets shipped with the console, applied on top of a preset
// in the builder screen. Values are strings because the settings map the
// builder sends to POST /api/worlds and /api/schema/preview is
// Record<string, string> (the server's field registry parses per field type).

export interface Recipe {
  id: string;
  name: string;
  description: string;
  preset: "phase1" | "phase2";
  settings: Record<string, string>;
}

export const RECIPES: Recipe[] = [
  {
    id: "bare-phase2",
    name: "Bare phase 2",
    description: "Phase 2 preset defaults, no settings overridden.",
    preset: "phase2",
    settings: {},
  },
  {
    id: "chemistry-field-phase22-base",
    name: "Chemistry field (Phase 22 base)",
    description: "The chemistry-field base settings from Phase 22 layered on phase2.",
    preset: "phase2",
    settings: {
      cells_x: "64",
      cells_y: "64",
      initial_organisms: "0",
      max_entities: "4000",
      "origin.mode": "scratch",
      "genome2.enabled": "true",
      "genome2.mutation.duplication_q16": "6554",
      "genome2.mutation.deletion_q16": "655",
      "genome2.mutation.insertion_q16": "0",
      "genome2.mutation.transposition_q16": "0",
      "genome2.caps.max_loci_per_chromosome": "160",
      "genome2.caps.max_nodes": "160",
      "genome2.caps.max_edges": "160",
      "genome2.caps.max_edges_per_node": "32",
      "genome2.caps.max_genome_bytes": "16384",
      "morphology.enabled": "true",
      "morphology.caps.max_modules": "64",
      "morphology.caps.lattice_radius": "8",
      "morphology.caps.max_growth_steps": "16",
      "morphology.base_node_budget": "4",
      "chemistry.enabled": "true",
      "chemistry.field_steps_per_tick": "1",
      "chemistry.microbial_enabled": "true",
      "chemistry.abiogenesis_enabled": "true",
      "chemistry.mutation_q16": "4096",
      "chemistry.excretion_fraction_q16": "32768",
      "chemistry.remains_fraction_q16": "32768",
      "transition.enabled": "true",
      "transition.check_interval_ticks": "100",
      "transition.density_floor_milli": "4000",
      "transition.persistence_checks": "5",
      "transition.aggregation_step_min": "1",
      "transition.organism_energy_milli": "4000",
      "transition.max_organisms_per_event": "4",
      "transition.max_materializations_per_tick": "64",
      "chemistry.consumption_fraction_q16": "65536",
    },
  },
  {
    id: "youngest-first-phase21-probe",
    name: "Youngest first (Phase 21 probe)",
    description: "The Phase 22 chemistry-field base with descending intake order (Phase 21 probe).",
    preset: "phase2",
    settings: {
      cells_x: "64",
      cells_y: "64",
      initial_organisms: "0",
      max_entities: "4000",
      "origin.mode": "scratch",
      "genome2.enabled": "true",
      "genome2.mutation.duplication_q16": "6554",
      "genome2.mutation.deletion_q16": "655",
      "genome2.mutation.insertion_q16": "0",
      "genome2.mutation.transposition_q16": "0",
      "genome2.caps.max_loci_per_chromosome": "160",
      "genome2.caps.max_nodes": "160",
      "genome2.caps.max_edges": "160",
      "genome2.caps.max_edges_per_node": "32",
      "genome2.caps.max_genome_bytes": "16384",
      "morphology.enabled": "true",
      "morphology.caps.max_modules": "64",
      "morphology.caps.lattice_radius": "8",
      "morphology.caps.max_growth_steps": "16",
      "morphology.base_node_budget": "4",
      "chemistry.enabled": "true",
      "chemistry.field_steps_per_tick": "1",
      "chemistry.microbial_enabled": "true",
      "chemistry.abiogenesis_enabled": "true",
      "chemistry.mutation_q16": "4096",
      "chemistry.excretion_fraction_q16": "32768",
      "chemistry.remains_fraction_q16": "32768",
      "transition.enabled": "true",
      "transition.check_interval_ticks": "100",
      "transition.density_floor_milli": "4000",
      "transition.persistence_checks": "5",
      "transition.aggregation_step_min": "1",
      "transition.organism_energy_milli": "4000",
      "transition.max_organisms_per_event": "4",
      "transition.max_materializations_per_tick": "64",
      "chemistry.consumption_fraction_q16": "65536",
      "physiology.intake_order": "descending",
    },
  },
];
